name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  stylelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm i
      - run: npm run dist
      - name: Lint source files
        run: npx stylelint --fix
      - name: Look for unused stylelint:disable lines
        run: npm run stylelint -- --report-needless-disables
      - name: Push up any fixes
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          set +e
          git status | grep modified
          if [ $? -eq 0 ]
          then
              set -e
              git stash
              git remote update
              git fetch
              git checkout --track origin/$GITHUB_HEAD_REF
              git config --local user.email "actions@github.com"
              git config --local user.name "Actions Auto Build"
              git stash pop
              git add src
              git commit -m "Stylelint auto-fixes"
              git push
          else
              set -e
              echo "No changes since last run"
          fi

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm i
      - name: Lint workflow files
        run: npm run eslint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm i
      - name: Jest
        run: npm test
